#!/bin/bash -e

this=`basename $0`

sitedir=$1

# Create temporary index file for git and remove it on exit
export GIT_INDEX_FILE=`pwd`/git-tmp-index.cri-resmgr.`date +%s`
trap "rm -f '$GIT_INDEX_FILE'" EXIT


# Create a git tree object of the content
git --work-tree "$sitedir" add .

git_tree_obj=`git write-tree`


# Don't create empty commits
old_tree_obj=`git rev-parse --verify gh-pages^{tree}`

if [ $git_tree_obj = $old_tree_obj ]; then
    echo "nothing to commit, gh-pages branch already up-to-date"
    exit 0
fi


# Create a new commit and update gh-pages branch
commit_msg=`echo -e "Update documentation\n\nAuto-generated by '$this'"`
git_commit_obj=`git commit-tree -p gh-pages -m "$commit_msg" $git_tree_obj`

git update-ref refs/heads/gh-pages $git_commit_obj

echo "gh-pages branch successfully updated"
