name: Docs
on:
  push:
    branches: ["devel/documentation-overhaul/hugo"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out our repo
      uses: actions/checkout@v2

    - name: Fetch gh-pages branch
      run: git fetch --no-tags --prune --depth=1 origin refs/heads/gh-pages:refs/heads/gh-pages

    - name: Build docs
      run: |
        git config user.name "Github Actions"
        git config user.email "no-reply@github.com"
        make update-gh-pages

    - name: Deploy docs
      run: git push -f https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
