name: Security Scanning

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  trivy-scan-code:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Trivy in fs mode
      continue-on-error: true
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        exit-code: 1
        list-all-pkgs: true
        format: template
        template: @trivy-csv.tpl
        output: trivy-report.csv

    - name: Update trivy CSV report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy-report.csv

  codeQL-scanning:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: go

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Upload result to GitHub Code Scanning
      if: ${{ github.event_name != 'pull_request' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: codeql.sarif
          wait-for-processing: true
